[[example]]
path = "examples/bools_and_nils.tn"
check_exit = 0
run_exit = 0
stdout = '''{true, {false, {nil, "hello world"}}}
'''
status = "active"

[[example]]
path = "examples/parity/01-literals/atom_expression.tn"
check_exit = 0
run_exit = 0
stdout = ''':ok
'''
status = "active"

[[example]]
path = "examples/parity/01-literals/bool_nil_string.tn"
check_exit = 0
run_exit = 0
stdout = '''{true, {false, {nil, "hello"}}}
'''
status = "active"

[[example]]
path = "examples/parity/01-literals/float_and_int.tn"
check_exit = 0
run_exit = 0
stdout = '''{1, 3.14}
'''
status = "active"

[[example]]
path = "examples/parity/01-literals/heredoc_multiline.tn"
check_exit = 0
run_exit = 0
stdout = '''"
    line1
    line2
    "
'''
status = "active"

[[example]]
path = "examples/parity/01-literals/interpolation_basic.tn"
check_exit = 0
run_exit = 0
stdout = '''"hello 3"
'''
status = "active"

[[example]]
path = "examples/parity/01-literals/numeric_separators.tn"
check_exit = 0
run_exit = 0
stdout = '''{1000000, {1500, 10000.50}}
'''
status = "active"

[[example]]
path = "examples/parity/01-literals/hex_octal_binary.tn"
check_exit = 0
run_exit = 0
stdout = '''{255, {63, 10}}
'''
status = "active"

[[example]]
path = "examples/parity/01-literals/char_literals.tn"
check_exit = 0
run_exit = 0
stdout = '''{97, {122, 65}}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/arithmetic_basic.tn"
check_exit = 0
run_exit = 0
stdout = '''{3, {2, {8, 5}}}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/comparison_set.tn"
check_exit = 0
run_exit = 0
stdout = '''{true, {true, {true, {true, {true, true}}}}}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/concat_and_list_ops.tn"
check_exit = 0
run_exit = 0
stdout = '''{"hello world", {[1, 2, 3, 4], [1, 3]}}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/logical_keywords.tn"
check_exit = 0
run_exit = 0
stdout = '''{false, {true, false}}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/logical_short_circuit.tn"
check_exit = 0
run_exit = 0
stdout = '''{false, {true, false}}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/membership_and_range.tn"
check_exit = 0
run_exit = 0
stdout = '''{true, {false, true}}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/strict_equality.tn"
check_exit = 0
run_exit = 0
stdout = '''{true, {false, {true, true}}}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/div_rem.tn"
check_exit = 0
run_exit = 0
stdout = '''{3, 1}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/not_in.tn"
check_exit = 0
run_exit = 0
stdout = '''{true, false}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/bitwise_operators.tn"
check_exit = 0
run_exit = 0
stdout = '''{1, {7, {3, {-6, {16, 4}}}}}
'''
status = "active"

[[example]]
path = "examples/parity/02-operators/stepped_range.tn"
check_exit = 0
run_exit = 0
stdout = '''[1, 4, 7, 10]
'''
status = "active"

[[example]]
path = "examples/parity/03-collections/keyword_literal_single_entry.tn"
check_exit = 0
run_exit = 0
stdout = '''[ok: 1]
'''
status = "active"

[[example]]
path = "examples/parity/03-collections/list_literal.tn"
check_exit = 0
run_exit = 0
stdout = '''[1, 2, 3]
'''
status = "active"

[[example]]
path = "examples/parity/03-collections/map_dot_and_index_access.tn"
check_exit = 0
run_exit = 0
stdout = '''{42, 42}
'''
status = "active"

[[example]]
path = "examples/parity/03-collections/map_literal_single_entry.tn"
check_exit = 0
run_exit = 0
stdout = '''%{:ok => 1}
'''
status = "active"

[[example]]
path = "examples/parity/03-collections/map_fat_arrow_literal.tn"
check_exit = 0
run_exit = 0
stdout = '''%{"status" => 200, 1 => true, false => :nope}
'''
status = "active"

[[example]]
path = "examples/parity/03-collections/map_update_single_key.tn"
check_exit = 0
run_exit = 0
stdout = '''%{:a => 2}
'''
status = "active"

[[example]]
path = "examples/parity/03-collections/struct_literal_update_pattern.tn"
check_exit = 0
run_exit = 0
stdout = '''{%{:__struct__ => :User, :name => "A", :age => 43}, {"A", 43}}
'''
status = "active"

[[example]]
path = "examples/parity/03-collections/tuple_literal_and_match.tn"
check_exit = 0
run_exit = 0
stdout = '''{1, {2, {3, 4}}}
'''
status = "active"

[[example]]
path = "examples/parity/04-patterns/case_atom_and_wildcard.tn"
check_exit = 0
run_exit = 0
stdout = '''2
'''
status = "active"

[[example]]
path = "examples/parity/04-patterns/case_list_bind.tn"
check_exit = 0
run_exit = 0
stdout = '''3
'''
status = "active"

[[example]]
path = "examples/parity/04-patterns/case_map_arrow_pattern.tn"
check_exit = 0
run_exit = 0
stdout = '''42
'''
status = "active"

[[example]]
path = "examples/parity/04-patterns/case_tuple_bind.tn"
check_exit = 0
run_exit = 0
stdout = '''42
'''
status = "active"

[[example]]
path = "examples/parity/04-patterns/match_operator_bindings.tn"
check_exit = 0
run_exit = 0
stdout = '''{1, 2}
'''
status = "active"

[[example]]
path = "examples/parity/04-patterns/pin_pattern_and_guard.tn"
check_exit = 0
run_exit = 0
stdout = '''20
'''
status = "active"

[[example]]
path = "examples/parity/04-patterns/bitstring_pattern_basic.tn"
check_exit = 0
run_exit = 0
stdout = '''{1, {2, 3}}
'''
status = "active"

[[example]]
path = "examples/parity/05-functions/anonymous_fn_capture_invoke.tn"
check_exit = 0
run_exit = 0
stdout = '''{10, 6}
'''
status = "active"

[[example]]
path = "examples/parity/05-functions/function_capture_named_arity.tn"
check_exit = 0
run_exit = 0
stdout = '''42
'''
status = "active"

[[example]]
path = "examples/parity/05-functions/function_capture_multi_clause_anon.tn"
check_exit = 0
run_exit = 0
stdout = '''{42, {7, 0}}
'''
status = "active"

[[example]]
path = "examples/parity/05-functions/default_args.tn"
check_exit = 0
run_exit = 0
stdout = '''{5, 10}
'''
status = "active"

[[example]]
path = "examples/parity/05-functions/function_guards_when.tn"
check_exit = 0
run_exit = 0
stdout = '''{1, 2}
'''
status = "active"

[[example]]
path = "examples/parity/05-functions/guard_builtins_parity.tn"
check_exit = 0
run_exit = 0
stdout = '''{{:integer, :binary}, {{:list, {:map, {:nil, :other}}}, {:float, {:number, {:atom, {:tuple, :fallback}}}}}}
'''
status = "active"

[[example]]
path = "examples/parity/05-functions/multi_clause_pattern_dispatch.tn"
check_exit = 0
run_exit = 0
stdout = '''{1, 2}
'''
status = "active"

[[example]]
path = "examples/parity/05-functions/private_defp_visibility.tn"
check_exit = 0
run_exit = 0
stdout = '''42
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/cond_branches.tn"
check_exit = 0
run_exit = 0
stdout = '''2
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/if_unless.tn"
check_exit = 0
run_exit = 0
stdout = '''{1, 3}
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/with_else_fallback.tn"
check_exit = 0
run_exit = 0
stdout = ''':failed
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/with_happy_path.tn"
check_exit = 0
run_exit = 0
stdout = '''30
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/alias_import_use_require.tn"
check_exit = 0
run_exit = 0
stdout = '''14
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/import_only_except_semantics.tn"
check_exit = 0
run_exit = 0
stdout = '''{42, "ok!"}
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/use_require_scoped_semantics.tn"
check_exit = 0
run_exit = 0
stdout = '''42
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/module_attributes_doc.tn"
check_exit = 0
run_exit = 0
stdout = '''42
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/module_qualified_calls.tn"
check_exit = 0
run_exit = 0
stdout = '''30
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/protocol_defimpl_dispatch.tn"
check_exit = 0
run_exit = 0
stdout = '''{2, {1, 9}}
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/project_multifile_pipeline"
check_exit = 0
run_exit = 0
stdout = '''300
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/module_special_form.tn"
check_exit = 0
run_exit = 0
stdout = ''':Demo
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/env_special_form.tn"
check_exit = 0
run_exit = 0
stdout = ''':Demo
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/nested_defmodule.tn"
check_exit = 0
run_exit = 0
stdout = ''':hi
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/alias_shorthand_forms.tn"
check_exit = 0
run_exit = 0
stdout = '''42
'''
status = "active"

[[example]]
path = "examples/parity/07-modules/module_attribute_value.tn"
check_exit = 0
run_exit = 0
stdout = '''42
'''
status = "active"

[[example]]
path = "examples/parity/08-errors/host_call_and_protocol_dispatch.tn"
check_exit = 0
run_exit = 0
stdout = '''"hello interop"
'''
status = "active"

[[example]]
path = "examples/parity/08-errors/ok_err_constructors.tn"
check_exit = 0
run_exit = 0
stdout = '''{ok(42), err("failed")}
'''
status = "active"

[[example]]
path = "examples/parity/08-errors/question_operator_err_bubble.tn"
check_exit = 0
run_exit = 1
stderr_contains = '''error: runtime returned err("bubbly")'''
status = "active"

[[example]]
path = "examples/parity/08-errors/question_operator_success.tn"
check_exit = 0
run_exit = 0
stdout = '''15
'''
status = "active"

[[example]]
path = "examples/parity/99-stretch/comments_hash.tn"
check_exit = 0
run_exit = 0
stdout = '''1
'''
status = "active"

[[example]]
path = "examples/parity/99-stretch/noparen_calls.tn"
check_exit = 0
run_exit = 0
stdout = '''2
'''
status = "active"

[[example]]
path = "examples/parity/99-stretch/list_cons_pattern.tn"
check_exit = 0
run_exit = 0
stdout = '''{1, [2, 3]}
'''
status = "active"

[[example]]
path = "examples/parity/99-stretch/map_colon_pattern.tn"
check_exit = 0
run_exit = 0
stdout = '''42
'''
status = "active"

[[example]]
path = "examples/parity/99-stretch/multi_entry_map_literal.tn"
check_exit = 0
run_exit = 0
stdout = '''%{:a => 1, :b => 2}
'''
status = "active"

[[example]]
path = "examples/parity/99-stretch/multi_entry_keyword_literal.tn"
check_exit = 0
run_exit = 0
stdout = '''[a: 1, b: 2]
'''
status = "active"

[[example]]
path = "examples/parity/99-stretch/sigils.tn"
check_exit = 0
run_exit = 0
stdout = '''"hello"
'''
status = "active"

[[example]]
path = "examples/parity/99-stretch/bitstring_binary.tn"
check_exit = 0
run_exit = 0
stdout = '''[1, 2, 3]
'''
status = "active"

[[example]]
path = "examples/parity/99-stretch/sigils_extended.tn"
check_exit = 0
run_exit = 0
stdout = '''["foo", "bar", "baz"]
'''
status = "active"

[[example]]
path = "examples/parity/99-stretch/bitstring_byte_size.tn"
check_exit = 0
run_exit = 0
stdout = '''{3, 24}
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/for_single_generator.tn"
check_exit = 0
run_exit = 0
stdout = '''[2, 4, 6]
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/for_multi_generator.tn"
check_exit = 0
run_exit = 0
stdout = '''[{1, 3}, {1, 4}, {2, 3}, {2, 4}]
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/for_into.tn"
check_exit = 0
run_exit = 0
stdout = '''[0, 2, 4]
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/for_into_map.tn"
check_exit = 0
run_exit = 0
stdout = '''%{:seed => 0, 1 => 10, 2 => 20}
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/for_into_keyword.tn"
check_exit = 0
run_exit = 0
stdout = '''[seed: 0, v: 1, v: 2]
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/for_generator_guard.tn"
check_exit = 0
run_exit = 0
stdout = '''[3, 4]
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/for_into_runtime_fail.tn"
check_exit = 0
run_exit = 1
stderr_contains = '''error: for into map expects tuple {key, value}, found int'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/for_reduce.tn"
check_exit = 0
run_exit = 0
stdout = '''6
'''
status = "active"

[[example]]
path = "examples/parity/06-control-flow/for_reduce_fail.tn"
check_exit = 1
run_exit = 1
stderr_contains = '''error: for options 'reduce' and 'into' cannot be combined'''
status = "active"

[[example]]
path = "examples/parity/08-errors/try_rescue_success.tn"
check_exit = 0
run_exit = 0
stdout = '''"oops"
'''
status = "active"

[[example]]
path = "examples/parity/08-errors/structured_raise_rescue_module.tn"
check_exit = 0
run_exit = 0
stdout = '''{"bad input", 42}
'''
status = "blocked"
blocked_reason = "c backend try helper cannot lower map constructor ops inside try/rescue yet"

[[example]]
path = "examples/parity/08-errors/raise_fail.tn"
check_exit = 1
run_exit = 1
stderr_contains = '''undefined symbol 'missing''''
status = "active"

[[example]]
path = "examples/parity/08-errors/try_catch_success.tn"
check_exit = 0
run_exit = 0
stdout = '''"caught oops"
'''
status = "active"

[[example]]
path = "examples/parity/08-errors/try_after_success.tn"
check_exit = 0
run_exit = 0
stdout = ''':ok
'''
status = "active"

[[example]]
path = "examples/parity/08-errors/try_rescue_catch_after_success.tn"
check_exit = 0
run_exit = 0
stdout = '''"caught fallback"
'''
status = "active"

# --- 10-idiomatic suite (Phase 7) ---

[[example]]
path = "examples/parity/10-idiomatic/closures_and_captures.tn"
check_exit = 0
run_exit = 0
stdout = '''{10, [2, 4, 6]}
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/cond_expression.tn"
check_exit = 0
run_exit = 0
stdout = '''"numbers work"
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/error_handling.tn"
check_exit = 0
run_exit = 0
stdout = '''"caught the error"
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/fibonacci.tn"
check_exit = 0
run_exit = 0
stdout = '''{0, 55}
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/fizzbuzz.tn"
check_exit = 0
run_exit = 0
stdout = '''[1, 2, "Fizz", 4, "Buzz", "Fizz", 7, 8, "Fizz", "Buzz", 11, "Fizz", 13, 14, "FizzBuzz"]
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/keyword_filtering.tn"
check_exit = 0
run_exit = 0
stdout = '''{[2, 3], 5}
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/list_processing.tn"
check_exit = 0
run_exit = 0
stdout = '''{[8, 2, 4, 6], 45}
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/map_transforms.tn"
check_exit = 0
run_exit = 0
stdout = '''{"Alice", 31}
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/multi_generator_grid.tn"
check_exit = 0
run_exit = 0
stdout = '''{[{1, :a}, {1, :b}, {2, :a}, {2, :b}, {3, :a}, {3, :b}], [{0, 1}, {0, 2}, {1, 0}, {1, 2}, {2, 0}, {2, 1}]}
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/pattern_matching_pipeline.tn"
check_exit = 0
run_exit = 0
stdout = '''"positive"
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/pipe_chain.tn"
check_exit = 0
run_exit = 0
stdout = '''"result: 5"
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/pipeline_transform.tn"
check_exit = 0
run_exit = 0
stdout = '''60
'''
status = "active"

[[example]]
path = "examples/parity/10-idiomatic/with_chain.tn"
check_exit = 0
run_exit = 0
stdout = '''{30, :not_found}
'''
status = "active"
